const fs = require("fs");
const path = require("path");

const { resolvePackageRoot } = require("./local-config");

const CARTFILE_LINE =
  /^(binary|github)\s+"([^"]+)"\s+(==|~>)\s+(.+)$|^(binary|github)\s+"([^"]+)"\s+"([^"]+)"$/;

function frameworkNameFromUrl(url) {
  const fileName = path.basename(url);
  if (fileName === "Polyline") {
    return "Polyline";
  }
  const base = fileName.replace(/\.json$/, "");
  return base.replace(/-\d+\.\d+\.\d+$/, "");
}

function parseCartfile(contents) {
  const entries = [];
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const match = line.match(CARTFILE_LINE);
    if (!match) {
      throw new Error(`Unsupported Cartfile line: ${rawLine}`);
    }

    if (match[1]) {
      entries.push({
        kind: match[1],
        url: match[2],
        operator: match[3],
        version: match[4].trim(),
        frameworkName: frameworkNameFromUrl(match[2]),
        line,
      });
      continue;
    }

    entries.push({
      kind: match[5],
      url: match[6],
      operator: null,
      version: match[7].trim(),
      frameworkName: frameworkNameFromUrl(match[6]),
      line,
    });
  }
  return entries;
}

function readCartfile(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing Cartfile: ${filePath}`);
  }
  return parseCartfile(fs.readFileSync(filePath, "utf8"));
}

function mergeCartfileEntries(entryGroups) {
  const merged = new Map();

  for (const entries of entryGroups) {
    for (const entry of entries) {
      const existing = merged.get(entry.frameworkName);
      if (!existing) {
        merged.set(entry.frameworkName, entry);
        continue;
      }

      if (existing.line === entry.line) {
        continue;
      }

      throw new Error(
        `Cartfile conflict for ${entry.frameworkName}: ` +
          `"${existing.line}" vs "${entry.line}"`,
      );
    }
  }

  return [...merged.values()].sort((a, b) =>
    a.frameworkName.localeCompare(b.frameworkName),
  );
}

function renderCartfile(entries, headerLines = []) {
  const lines = [
    "# Generated by scripts/generate-ios-cartfile.js",
    "# Do not edit manually.",
    ...headerLines,
    "",
    ...entries.map((entry) => entry.line),
    "",
  ];
  return lines.join("\n");
}

function resolvePackageCartfile(repoRoot, packageSpec, searchPaths) {
  if (packageSpec.workspacePath) {
    const workspaceCartfile = path.join(
      repoRoot,
      packageSpec.workspacePath,
      "Cartfile",
    );
    if (!fs.existsSync(workspaceCartfile)) {
      throw new Error(`Missing workspace Cartfile for ${packageSpec.name}`);
    }
    return readCartfile(workspaceCartfile);
  }

  const packageRoot = resolvePackageRoot(
    repoRoot,
    packageSpec.name,
    searchPaths,
  );
  if (!packageRoot) {
    throw new Error(
      `Missing installed Cartfile for ${packageSpec.name}. Install dependencies first.`,
    );
  }

  const installedCartfile = path.join(packageRoot, "Cartfile");
  if (!fs.existsSync(installedCartfile)) {
    throw new Error(
      `Missing Cartfile in ${packageRoot} for ${packageSpec.name}.`,
    );
  }
  return readCartfile(installedCartfile);
}

function checkGeneratedCartfile({ outputPath, mergedEntries, headerLines }) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";
  if (!current.trim()) {
    throw new Error(`Missing ${outputPath}`);
  }

  if (!mergedEntries) {
    parseCartfile(current);
    console.log("Validated committed Cartfile syntax.");
    return;
  }

  const rendered = renderCartfile(mergedEntries, headerLines);
  if (current !== rendered) {
    throw new Error(
      `${outputPath} is out of date. Run: node scripts/generate-ios-cartfile.js`,
    );
  }
  console.log("Cartfile is up to date.");
}

module.exports = {
  frameworkNameFromUrl,
  parseCartfile,
  readCartfile,
  mergeCartfileEntries,
  renderCartfile,
  resolvePackageCartfile,
  checkGeneratedCartfile,
};
