# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require("react-native/scripts/react_native_pods.rb")
node_require("react-native-permissions/scripts/setup.rb")
  
#require Pod::Executable.execute_command('node', ['-p',
#  'require.resolve(
#    "react-native/scripts/react_native_pods.rb",
#    {paths: [process.argv[1]]},
#  )', __dir__]).strip
platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNReanimated')
      def pod.build_type;
      Pod::BuildType.static_library
      end
    end
  end
end

target 'RNMapsSampleApp' do
  use_frameworks! :linkage => :dynamic

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => "../node_modules/react-native",
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => false,  # Explicitly disable New Architecture for compatibility
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Manually link native modules
  pod 'react-native-restart', :path => '../node_modules/react-native-restart'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-masked-view/masked-view'

  target 'RNMapsSampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Fix permissions on Carthage dSYM Info.plist files to avoid permission errors
    # React Native's post-install hook tries to read these files
    Dir.glob("#{__dir__}/Carthage/Build/**/dSYMs/**/Info.plist").each do |plist|
      File.chmod(0644, plist) if File.exist?(plist) && !File.writable?(plist)
    end
    
    # Convert binary plists to XML format to avoid UTF-8 encoding errors
    # This is necessary for Carthage xcframeworks which may have binary plists
    # Do this before react_native_post_install to prevent encoding errors
    Dir.glob("#{__dir__}/Carthage/Build/**/*.framework/Info.plist").each do |plist|
      if File.exist?(plist) && File.readable?(plist)
        system("plutil -convert xml1 '#{plist}' 2>/dev/null")
      end
      end

    #installer.generated_projects.each do |project|
    #      project.targets.each do |target|
    #          target.build_configurations.each do |config|
    #              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    #           end
    #      end
    #end
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false
    )
  end
end
