yarnPath: .yarn/releases/yarn-4.10.3.cjs
nodeLinker: node-modules
nmHoistingLimits: workspaces
npmScopes:
  trimblemaps:
    npmRegistryServer: "https://trimblemaps.jfrog.io/artifactory/api/npm/trimblemaps-npm/"
